# task migrate-up CONFIG_PATH=./config/local.yaml
version: "3"

tasks:
  migrate-up:
    aliases:
      - up
    desc: "Apply all up migrations"
    cmds:
      - goose -dir "./migrations" postgres "$(yq eval '.storage.dsn' {{.CONFIG_PATH}})" up